# Generated by Django 3.2.3 on 2021-07-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='percentage',
            field=models.IntegerField(max_length=99),
        ),
    ]
