# Generated by Django 3.2.3 on 2021-07-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_offer_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='percentage',
            field=models.IntegerField(max_length=2),
        ),
    ]
